# Generated by Django 4.2.6 on 2023-11-02 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='product_tb',
        ),
    ]
